name: 72h Free Poster

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch: {}       # allow manual run

jobs:
  run-poster:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # to commit posted_state.json updates
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run poster
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          REDDIT_SUB_SLOTSNIPER: ${{ secrets.REDDIT_SUB_SLOTSNIPER }}
          REDDIT_SUB_TRIALKILLER: ${{ secrets.REDDIT_SUB_TRIALKILLER }}
          DISCORD_WEBHOOK_URLS: ${{ secrets.DISCORD_WEBHOOK_URLS }}
          SLOTSNIPER_BOT_TOKEN: ${{ secrets.SLOTSNIPER_BOT_TOKEN }}
          TRIALKILLER_BOT_TOKEN: ${{ secrets.TRIALKILLER_BOT_TOKEN }}
          SS_CHANNEL: ${{ secrets.SS_CHANNEL }}
          TK_CHANNEL: ${{ secrets.TK_CHANNEL }}
        run: python poster_free.py

      - name: Commit state
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add posted_state.json
            git commit -m "Update posting state [skip ci]" || true
            git push
          fi
